# Model configurations
models:
  summarization:
    default: "facebook/bart-large-cnn"
    options:
      - "facebook/bart-large-cnn"
      - "google/pegasus-xsum"
  
  classification:
    default: "distilbert-base-uncased-finetuned-sst-2-english"
    zero_shot_default: "facebook/bart-large-mnli"
  
  translation:
    default: "Helsinki-NLP/opus-mt-en-de"
    options:
      - "Helsinki-NLP/opus-mt-en-de"
      - "Helsinki-NLP/opus-mt-fr-en"

# Training defaults
training:
  batch_size: 16
  learning_rate: 2e-5
  num_epochs: 3
  logging_steps: 10